# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - cora using Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (or Azure Container Registry if needed)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image from Dockerfile
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/cora-app:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/cora-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Step 5: Deploy the Docker image to Azure Web App
      - name: 'Deploy to Azure Web App using Docker'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cora'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FC5A83F3B5AE4483B3769C088176AC18 }}
          images: 'yecm/cora-app:latest'
